#
# Global-configurations
#

equals(SKIP_APP_GLOBAL_CONF, true): return()
SKIP_APP_GLOBAL_CONF = true

load(extras)

# Which variable to trace:
QMAKE_WATCH = OUT_PWD

ROOT_PWD=$$PWD
## Same as $$OUT_PWD but in root
ROOT_OUT_PWD=$$shadowed($$PWD)

equals(ROOT_OUT_PWD, $$PWD) {
    error(Building in source-dir is not supported.)
}

include($$PWD/config/globals.pri)
include($$PWD/test/config/functions.pri)
